[package]
name = "socket_tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
serde = "1.0.192"
tokio = { version = "1.35.0", features = ["full"] }